services:
    ktor-app-prod:
        build: .
        ports:
            - "8083:8083"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
            - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
        depends_on:
            - db-prod
        volumes:
            - ./.env.prod:/app/.env
        env_file:
            - .env.prod

    db-prod:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin-prod:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_PORT=${PGADMIN_PORT}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db-prod
        volumes:
            - pgadmin_prod_data:/var/lib/pgadmin

    tunnel:
        image: cloudflare/cloudflared:latest
        depends_on:
            - ktor-app-prod
        container_name: cloudflared-tunnel
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        environment:
            - TUNNEL_TOKEN=${TUNNEL_TOKEN}

#    redis-prod:
#        image: redis:7-alpine
#        environment:
#            - REDIS_PORT=${REDIS_PORT}
#        ports:
#            - "${REDIS_PORT:-6379}:6379"
#        volumes:
#            - ./.env.prod:/app/.env
#
#    loki-prod:
#        image: grafana/loki:2.9.0
#        ports:
#            - "3100:3100"
#
#    promtail-prod:
#        image: grafana/promtail:2.9.0
#        volumes:
#            - /var/lib/docker/containers:/var/lib/docker/containers:ro
#            - ./promtail-config.yml:/etc/promtail/config.yml
#        command: -config.file=/etc/promtail/config.yml
#
#    grafana-prod:
#        image: grafana/grafana:latest
#        environment:
#            - GRAFANA_PORT=${GRAFANA_PORT}
#        ports:
#            - "${GRAFANA_PORT}:3002"

volumes:
    postgres_data:
    pgadmin_prod_data:
