services:
    ktor-app-dev:
        build: .
        ports:
            - "8084:8084"
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SECRET_KEY=${SECRET_KEY}
            - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
        depends_on:
            - db-dev
        volumes:
            - ./.env.dev:/app/.env
        env_file:
            - .env.dev

    db-dev:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin-dev:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_PORT=${PGADMIN_PORT}
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - db-dev
        volumes:
            - pgadmin_dev_data:/var/lib/pgadmin

    dozzle-dev:
        image: amir20/dozzle:latest
        container_name: dozzle-dev
        ports:
            - "9999:8090"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    tunnel-dev:
        image: cloudflare/cloudflared:latest
        depends_on:
            - ktor-app-dev
        container_name: cloudflared-tunnel
        restart: unless-stopped
        command: tunnel --no-autoupdate run
        environment:
            - TUNNEL_TOKEN=${TUNNEL_TOKEN}

volumes:
    postgres_data:
    pgadmin_dev_data:
