
[versions]
exposed-version = "0.57.0"
h2-version = "2.3.232"
koin-version = "3.5.6"
kotlin-version = "2.3.0"
logback-version = "1.4.14"
bcrypt = "0.10.2"
postgres-version = "42.7.4"
dotenv-version = "6.4.1"
asyncapi-version = "3.1.3"
ksp-version = "2.3.4"
ktor = "3.3.2"
hoplite-version = "2.7.5"
testcontainers-version = "1.19.7"
junit-version = "5.10.2"
mockk-version = "1.13.11"
junit = "6.0.1"
assertj = "3.27.3"
restAssured = "6.0.0"
flyway-version = "10.15.2"
firebase-admin-version = "9.2.0"

[libraries]
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging-jvm", version.ref = "ktor" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
h2 = { module = "com.h2database:h2", version.ref = "h2-version" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin-version" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }
bcrypt = { group = "at.favre.lib", name = "bcrypt", version.ref = "bcrypt" }
hikari  = { module = "com.zaxxer:HikariCP", version = "5.1.0" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres-version" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version = "0.53.0" }
dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv-version" }
ktor-server-rate-limit = { module = "io.ktor:ktor-server-rate-limit-jvm", version.ref = "ktor" }
ktor-server-rate-limiting = { module = "io.github.flaxoos:ktor-server-rate-limiting", version = "2.2.1" }
kotlin-asyncapi-ktor = { module = "org.openfolder:kotlin-asyncapi-ktor", version = "3.1.3" }
ktor-server-metrics = { module = "io.ktor:ktor-server-metrics", version.ref = "ktor" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor" }
ktor-server-openapi = { module = "io.ktor:ktor-server-openapi", version.ref = "ktor" }
ktor-server-http-redirect = { module = "io.ktor:ktor-server-http-redirect", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-simple-cache = { module = "com.ucasoft.ktor:ktor-simple-cache", version = "0.55.3" }
ktor-server-task-scheduling-core = { module = "io.github.flaxoos:ktor-server-task-scheduling-core", version = "2.2.1" }
ktor-server-task-scheduling-redis = { module = "io.github.flaxoos:ktor-server-task-scheduling-redis", version = "2.2.1" }
ktor-server-task-scheduling-mongodb = { module = "io.github.flaxoos:ktor-server-task-scheduling-mongodb", version = "2.2.1" }
ktor-server-task-scheduling-jdbc = { module = "io.github.flaxoos:ktor-server-task-scheduling-jdbc", version = "2.2.1" }
hoplite-core = { module = "com.sksamuel.hoplite:hoplite-core", version.ref = "hoplite-version" }
hoplite-hocon = { module = "com.sksamuel.hoplite:hoplite-hocon", version.ref = "hoplite-version" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers-version" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers-version" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "1.10.2" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk-version" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway-version" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase-admin-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-version" }
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway-version" }
